#!/bin/sh

echo "=== Start rcS ==="
# Создание консольного устройства
mount -n -t tmpfs none /dev
mknod -m 622 /dev/console c 5 1
mknod -m 666 /dev/null c 1 3
mknod -m 666 /dev/zero c 1 5
mknod -m 666 /dev/ptmx c 5 2
mknod -m 666 /dev/tty c 5 0 # <--
mknod -m 444 /dev/random c 1 8
mknod -m 444 /dev/urandom c 1 9

# Монтирование файловых систем
mount -t proc proc /proc
mount -t sysfs sysfs /sys
mount -t tmpfs tmpfs /tmp

# Инициализация устройств
echo /sbin/mdev > /proc/sys/kernel/hotplug
mdev -s

echo "=== Start /etc/start.sh ==="
/etc/start.sh

